### ISSUE TITLE
加pod支持吧

### ISSUE THREAD

**Issue by badboy-tian** [Yasashi/EBForeNotification#1]

**Comment by pikacode** [comment]
@tianqiujie  你好，这周内加 pod。还考虑针对不同 iOS 设备和系统增加几种样式。
另外想问一下，你用着是否正常。

**Comment by pikacode** [comment]
@tianqiujie 你好，已经加了 pod 'EBForeNotification'，最新 1.0.3 版本，修复了一些问题。

**Comment by pikacode** [comment]
@tianqiujie 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
