### ISSUE TITLE
Wrong fonts for iOS 10

### ISSUE THREAD

**Issue by dimovskidamjan** [Yasashi/EBForeNotification#10]
The fonts for the iOS10 style notification are wrong:
The title should be System Light 13, and the message System Regular 15. Please update these to achieve a more authentic experience for the users.

**Comment by pikacode** [comment]
@dimovskidamjan 
Maybe some pull requests? I'm so busy recently 😅

**Comment by dimovskidamjan** [comment]
@pikacode No problem, I will try to do this in the following days.

**Comment by pikacode** [comment]
@dimovskidamjan Thank you so much! ^。^

**Comment by pikacode** [comment]
@dimovskidamjan 
- And actually It seems that there is some shadows behind the iOS 10 banner, I tried to add it, but failed 😅
- iOS 10 foreground notification banner is supported by system, maybe there is no need to create a `EBBannerView` anymore

**Comment by dimovskidamjan** [comment]
@pikacode I will refactor it to show the system banner on iOS 10 and still show EBBannerView for iOS 9, so both will be covered.

**Comment by Huang-Libo** [comment]
期待 iOS 10 的适配

**Comment by pikacode** [comment]
@Huang-Libo 哥们一起帮忙改进代码呗，提提 pull request。我最近确实太忙。

**Comment by Huang-Libo** [comment]
@pikacode 我还没看 EBForeNotification 的源码，有空先观摩观摩。

**Comment by pikacode** [comment]
@Huang-Libo 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by Huang-Libo** [comment]
@pikacode 资兹!
