### ISSUE TITLE
Wrong appName parameter

### ISSUE THREAD

**Issue by dimovskidamjan** [Yasashi/EBForeNotification#11]
This `NSDictionary *infoDictionary = [[NSBundle bundleForClass:[self class]] infoDictionary];` should be like this: `NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];` in order for the app name to be inserted in the notifications, otherwise EBForeNotification is inserted.

**Comment by pandaApe** [comment]
cocopods 上的1.0.7版本 还是 `NSDictionary *infoDictionary = [[NSBundle bundleForClass:[self class]] infoDictionary];` @pikacode

**Comment by pikacode** [comment]
其实我是想有个大更新的，但是太忙了，代码改到一半

**Comment by pandaApe** [comment]
哈哈，我们公司两个项目都在用。非常感谢。

**Comment by pikacode** [comment]
Hi @dimovskidamjan 
This repo will not update anymore, I suggest u to use [EBBannerView](https://github.com/pikacode/EBBannerView), a new pod which I refactored this, and it's also more powerfull with more features. :)

**Comment by pikacode** [comment]
@pandaApe 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
