### ISSUE TITLE
如果加title和subtitle就会崩溃

### ISSUE THREAD

**Issue by wangtian076** [Yasashi/EBForeNotification#12]
[__NSCFDictionary length]: unrecognized selector sent to instance 0x157a98e0
我的系统是iOS9.2.1

**Comment by pikacode** [comment]
应该是暂未适配 iOS 10 的推送 payload 字段导致的。
有空会进行更新，添加新的 UI 用于展示 title subtitle。
或者哥们你可以提个 pr 😄

**Comment by wangtian076** [comment]
![image](https://cloud.githubusercontent.com/assets/9692429/19637876/af6a5ace-9a03-11e6-85f2-4a17f3e6c68b.png)
是的。
pr是什么呢？

**Comment by pikacode** [comment]
pull request，你可以修改代码，然后提交给我，我就可以直接合并到这个项目中来了。
![image](https://cloud.githubusercontent.com/assets/12589575/19638144/1cd6e194-9a05-11e6-87c6-dc919b8658c6.png)

**Comment by pikacode** [comment]
@wangtian076 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by pikacode** [comment]
@wangtian076 
新的仓库支持自定义所有参数（包括 图标/标题/内容/时间 等等等等），不会再有这个 bug，欢迎使用 :)
