### ISSUE TITLE
建议优先采用CFBundleDisplayName

### ISSUE THREAD

**Issue by CoderKLTse** [Yasashi/EBForeNotification#15]
有的应用BundleDisplayName才是真正显示的App应用名，Bundle name则采用工程名或者开发内部自定义名字。我不知道有多少应用是这样子，或者你开放API让开发者自己选择，显示的内容（图标和App名称）。THX！
ps：EBForeNotification抛砖引玉，告诉我一种实现的方向，感谢！

**Comment by pikacode** [comment]
是啊，在dev分支里已经改了 ：），有空会更新。

**Comment by pikacode** [comment]
@CoderKLTse 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
