### ISSUE TITLE
动画导致Alert显示到了左上角

### ISSUE THREAD

**Issue by facetoface** [Yasashi/EBForeNotification#16]
情景：当推送过来的时候，我调用了作者的框架，如果此时的页面上有一个弹窗，系统的弹窗会显示到左上角

**Comment by pikacode** [comment]
@facetoface 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by pikacode** [comment]
@facetoface 
新的代码进行过重构，应该可以避免此类 bug，你可以再试试 :)

**Comment by ChiCo-li** [comment]
好的，谢谢啦。
