### ISSUE TITLE
监听点击弹窗的事件、用户点击以后可以取到推送内容为空

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [Yasashi/EBForeNotification#18]
2.监听点击弹窗的事件、用户点击以后可以取到推送内容、通过自定义推送中的 extra 字段处理自己的逻辑。如：
    add observer for "EBBannerViewDidClick", handle extra key/value

    {
        {
            aps:"alert":"推送内容",
            "sound":"sound",
            "badge":"3"
        },
            "key1":"跳转页面1"  //自定义此字段以跳转到相应页面
    }

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(eBBannerViewDidClick:) name:EBBannerViewDidClick object:nil];
    -(void)eBBannerViewDidClick:(NSNotification*)noti{
        if(noti[@"key1" == @"跳转页面1"]){
            //jump to page 1
        }
    }
按照方法执行的，但是 noti获取是null

**Comment by liunianhuaguoyanxi** [comment]
之前调用了           
 [EBForeNotification handleRemoteNotification:userInfo soundID:1312];
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(eBBannerViewDidClick:) name:EBBannerViewDidClick object:nil];

        }
            completionHandler(UIBackgroundFetchResultNewData);

**Comment by zeew** [comment]
我也是一样的问题，求助

**Comment by pikacode** [comment]
addObserver 写在哪里？

**Comment by pikacode** [comment]
@liunianhuaguoyanxi @zeew 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by pikacode** [comment]
@liunianhuaguoyanxi @zeew 
监听点击事件并传值或传 object，或自定义其它参数，均可以在以上新仓库中实现，欢迎使用 :)
