### ISSUE TITLE
这个开源项目是个静态库？

### ISSUE THREAD

**Issue by SatanWoo** [Yasashi/EBForeNotification#2]

**Comment by pikacode** [comment]
这两天会把源码发布出来，并且添加 pod ^_^

**Comment by pikacode** [comment]
@SatanWoo 所有源码已经放到 dev 分支上，欢迎交流 ^ ^

**Comment by SatanWoo** [comment]
多谢，抱歉，给你开了个issue，我这就close掉

**Comment by pikacode** [comment]
@SatanWoo 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
