### ISSUE TITLE
可否使用系统默认提示音

### ISSUE THREAD

**Issue by DNC-7** [Yasashi/EBForeNotification#21]
请问是否必须要指定一种声音？即使用户静音状态下也会收到提示音，这样似乎体验不好

**Comment by pikacode** [comment]
https://github.com/pikacode/EBForeNotification/releases/tag/1.0.7

**Comment by pikacode** [comment]
应该是做过静音检测的。

**Comment by DNC-7** [comment]
@pikacode 你好，请问接收到通知后，是不是还是无法在通知中心显示，只是有一个banner的提示

**Comment by pikacode** [comment]
接收到通知时，app如果在前台，通知是不会在通知中心展示的。跟这个库没有关系。

**Comment by Coder-ZJQ** [comment]
@ChenDongnan 如果希望在通知中心也显示的话可以手动添加个本地通知。

**Comment by pikacode** [comment]
@ChenDongnan @Coder-ZJQ 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by pikacode** [comment]
@ChenDongnan 
声音 id 设为 0 可以强制静音，更多自定义参数均可以在以上的新仓库中实现，欢迎使用 :)
