### ISSUE TITLE
问一下 展示时间默认多少，可以配置吗？

### ISSUE THREAD

**Issue by hujun1288** [Yasashi/EBForeNotification#22]
您好，非常喜欢您写的插件，谢谢分享，，
问一下 控件 展示时间默认多少，可以配置吗，或者可以配置不自动消失吗？

**Comment by coderBM** [comment]
默认我看配置写的是4.7秒 你自己可以更改他的代码  方法里写了个定时器 你可以修改下  里面也写了移除视图的方法  可以自己修改 或者给作者pr  估计也没更新了  你就自己修改下吧

**Comment by pikacode** [comment]
@hujun1288 @coderBM 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)

**Comment by pikacode** [comment]
@hujun1288 @coderBM 
自定义各个参数，可以在上面提供的新仓库实现，欢迎使用 :)

**Comment by hujun1288** [comment]
@pikacode 非常感谢，，
