### ISSUE TITLE
Crash when receiving notification of type: {title: <title>, body: <body}

### ISSUE THREAD

**Issue by yaniv-s** [Yasashi/EBForeNotification#24]
Notification 'alert' key can be both a string and a dictionary.
When sending the following notification:
`{"aps" : { "alert" : { title: "title", body: "text" } } }`

The application crashes on:
```
File: EBBannerView.m
-(NSString*) extractContentLabel:(NSDictionary*)userInfo{
    @throw [NSException exceptionWithName:NSInvalidArgumentException
                                   reason:@"aps['alert'] field malformed: it is neither a string nor a dictionary with key 'loc-key'"
                                 userInfo:nil];
```

Maybe it's a good idea never throw exceptions in production? It's good for debugging, but in production maybe the best thing would be logging it and not crashing the whole app.

Thanks! :)

**Comment by pikacode** [comment]
yes, considered this situation, and some codes designed not very well, I created a more powerful pod [EBBannerView](https://github.com/pikacode/EBBannerView), it can be used for not only notification, but also many other custom needs.
