### ISSUE TITLE
静音下声音没有设置么

### ISSUE THREAD

**Issue by LvJianfeng** [Yasashi/EBForeNotification#4]

**Comment by pikacode** [comment]
@LvJianfeng  你的意思是不是 静音下仍然会有声音提示

**Comment by LvJianfeng** [comment]
是的呢😬

**Comment by pikacode** [comment]
我这2天更新一下，加个静音的判断进去。

**Comment by LvJianfeng** [comment]
嗯嗯，感谢开源

**Comment by pikacode** [comment]
@LvJianfeng 现在 `dev` 分支上的代码已经可以支持你需要的功能了，用户静音的时候会振动，不会播声音了。新的版本过几天才会发布，你如果比较急可以直接先用 `dev` 分支的代码。

**Comment by LvJianfeng** [comment]
嗯嗯 好的 谢谢

**Comment by pikacode** [comment]
@LvJianfeng 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
