### ISSUE TITLE
获取 App Name这块 作了修改

### ISSUE THREAD

**Issue by DreamBuddy** [Yasashi/EBForeNotification#5]
![image](https://cloud.githubusercontent.com/assets/3683368/18738298/16cc4f88-80cd-11e6-8433-5e65cb37eca4.png)

**Comment by pikacode** [comment]
做了什么修改？

**Comment by DreamBuddy** [comment]
![image](https://cloud.githubusercontent.com/assets/3683368/18739218/a306e920-80d4-11e6-863c-176a1c7630ca.png)
这个地方

**Comment by pikacode** [comment]
明白了，下次更新改一下 ：）

**Comment by Zorodon** [comment]
// app名称
    NSString *appName = [infoDictionary objectForKey:@"CFBundleName"];
    if (!appName) {
        appName = [infoDictionary objectForKey:@"CFBundleDisplayName"];
    }
    //appName = @"input a app name here"; //if appName = nil, unsign this line and change it to you'r own app name.
    if (!appName) {
        assert(0);
    }

目前的代码里是不是写反了？？

**Comment by pikacode** [comment]
@DreamBuddy @z-ddong 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
