### ISSUE TITLE
hello ,iOS环境下,EBForeNotification和极光推送混用的时候,在杀死程序的情况下收到远程推送会闪退

### ISSUE THREAD

**Issue by LGLee** [Yasashi/EBForeNotification#6]
hello ,iOS环境下,EBForeNotification和极光推送混用的时候,在杀死程序的情况下收到远程推送会闪退.望解决.在前台的时候暂时没有发现问题,望解决一下

**Comment by pikacode** [comment]
「在杀死程序的情况下收到远程推送会闪退」，你的意思是不是杀死程序以后收到推送，点击推送横幅启动App，然后会闪退？

**Comment by LGLee** [comment]
就是在杀死情况 收到推送的  点击推送 ,闪一下,就退了

**Comment by LGLee** [comment]
无论是点击的推送列表还是横幅

**Comment by pikacode** [comment]
- EBForeNotification 会自动添加到 controller 上面展示，App 刚刚启动没有任何 controller，无法展示。建议你不要在 didFinishLaunching 里调用 EBForeNotification，选择合适的时机再调用。
- 如果你没有在 didFinishLaunching 里调用，那么你的闪退可能跟 EBForeNotification 无关。

**Comment by lai3d** [comment]
Tap推送横幅或者列表闪退。
我在这里调用EBForeNotification在iOS 9上也会闪退 - (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler

iOS 10上像下面这样没问题
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
     willPresentNotification:(UNNotification *)notification
       withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
  // Print message ID.
  NSDictionary *userInfo = notification.request.content.userInfo;
  NSLog(@"Message ID: %@", userInfo[@"gcm.message_id"]);
  
  // Print full message.
  NSLog(@"userInfo: %@", userInfo);
  
  [EBForeNotification handleRemoteNotification:userInfo soundID:1312 isIos10:YES];
  }
  
  // Receive data message on iOS 10 devices.
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
  // Print full message
  NSLog(@"remoteMessage %@", [remoteMessage appData]);
  }
  #endif

**Comment by lai3d** [comment]
在iOS 9上这么用就不会闪退了，判断下是否UIApplicationStateActive
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
  fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  if(NULL != userInfo && userInfo.count > 0) {
      // Print message ID.
      NSLog(@"Message ID: %@", userInfo[@"gcm.message_id"]);
  
  ```
  // Pring full message.
  NSLog(@"userInfo %@", userInfo);
  
  UIApplicationState state = [[UIApplication sharedApplication] applicationState];
  if (state == UIApplicationStateActive) {
      [EBForeNotification handleRemoteNotification:userInfo soundID:1312];
  }
  ```
  
  }
  completionHandler(UIBackgroundFetchResultNewData);
  }

**Comment by pikacode** [comment]
thx，我稍后自己考虑一下这块，把这些判断加到 EBForeNotification 里面。

**Comment by LGLee** [comment]
楼上正确,现在不闪退了,,,tks

**Comment by pikacode** [comment]
@LGLee @lai3d 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
