### ISSUE TITLE
Notification time is a constant

### ISSUE THREAD

**Issue by dimovskidamjan** [Yasashi/EBForeNotification#7]
@pikacode Why is the notification time a constant string with (I'm guessing) chinese characters? Why doesn't it read the current time? Are we supposed to set it somehow?

**Comment by pikacode** [comment]
@dimovskidamjan 
- When Apps receiving the notification on foreground, I think the time is "now" as usual, so I defined it a constant.
- And you can change it to other languages such as "now", but still a constant. Change it in 'EBForeNotification.h'

``` objc
static NSString *const EBBannerViewTimeText = @"现在";    //默认弹窗时间 default banner time
```
- if you want set it to different values, maybe I can provide a API about it in next version.

**Comment by dimovskidamjan** [comment]
@pikacode I understand, but you should make it localized, i.e. the string "now" should be localized according to the current locale of the device, which is already localized by default by Apple. See the attached image:
![screen shot 2016-10-05 at 4 23 55 pm](https://cloud.githubusercontent.com/assets/9072054/19117182/67dbae50-8b18-11e6-85b8-b0767eee38c2.png)

I wouldn't want to change it locally, because I'm using cocoapods, so the next time I update the pod my changes will be reverted and the issue will return. Could you please fix this and publish a new version of the pod?

**Comment by pikacode** [comment]
ok, I got it, I will fix it in few days. Maybe publish it during 10.08~10.16.  :)
now is on holidays..

**Comment by dimovskidamjan** [comment]
Thanks.
