### ISSUE TITLE
Alert View Position is top when push notification is handled.

### ISSUE THREAD

**Issue by yu0winter** [Yasashi/EBForeNotification#8]
UIAlerView在屏幕中间时，展示EBBannerView，UIAlertView的位置偏移到了左上角。

**Comment by yu0winter** [comment]
![Smaller icon](https://raw.githubusercontent.com/yu0winter/yu0winter.github.io/master/Error/iOS-Foreground-Push-Notification.png)

**Comment by yu0winter** [comment]
解决方法已提交（详情见Pull Request #9 ）
解决Bug：在AlerView展示的情况下，收到推送消息，结果AlertView被偏移到了屏幕的左上角。
解决方法：避免AlertView 和 Banner 加载在同一个ViewController上。
注，支持iOS8.0以上版本。

**Comment by pikacode** [comment]
@yu0winter 
你好，这个仓库已经不再维护，你可以使用新的仓库 [EBBannerView](https://github.com/pikacode/EBBannerView)。它对此进行了重构，并且提供更多你想不到的强大功能，欢迎使用 :)
